version: '3.8'
services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    command: ["redpanda", "start", "--overprovisioned", "1", "--memory", "1G", "--smp", "1"]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
    healthcheck:
      test: ["CMD", "bash", "-c", "rpk topic list || exit 0"]

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: pm_user
      POSTGRES_DB: pm_db
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pm_user"]

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

  ingestion:
    build: ./ingestion
    ports:
      - "8000:8000"
    depends_on:
      - redpanda
      - timescaledb
    environment:
      - REDPANDA_BOOTSTRAP=redpanda:9092
      - DATABASE_URL=postgresql://pm_user:example@timescaledb:5432/pm_db

volumes:
  timescale-data:
  qdrant-data: